In [ ]:
#Черкасов
#КВБО-04-22, Кудряшова Анна Александровна. Рабочая тетрадь №2 по дисциплине "Икусственный интеллект"

Задача 1.3.1
Создать матрицу 8 на 8 и заполнить её в шахматном порядке нулями и единицами

In [19]:
import numpy as np
matrix = np.array([0,1]*4*8)
matrix = matrix.reshape(8, 8)
matrix[0:9:2] = np.roll(matrix[0], 1)
for i in matrix:
  print(*i)


1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1


Задача 1.3.2
Создать матрицу 5 на 5 со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arange


In [12]:
import numpy as np
vector = np.arange(5)
matr = np.array([0]*25)
matr = matr.reshape(5,5)
for i in range(5):
    matr[i] = vector
for i in matr:
    print(*i)

0 1 2 3 4
0 1 2 3 4
0 1 2 3 4
0 1 2 3 4
0 1 2 3 4


Создать массив 3*3*3 со случайными значениями

In [15]:
import numpy as np
mas = np.random.random((3, 3, 3))
print(mas)

[[[0.40231369 0.46425745 0.69360519]
  [0.99182215 0.37079692 0.02358738]
  [0.12216061 0.48118022 0.80113858]]

 [[0.52632047 0.23739887 0.94784524]
  [0.28362959 0.91213567 0.48850227]
  [0.18850865 0.61628609 0.11071286]]

 [[0.82223014 0.29672404 0.29886554]
  [0.33855173 0.70376798 0.52117053]
  [0.61223912 0.38626313 0.09586336]]]


Создать матрицу с 0 внутри и 1 на границах

In [16]:
mas = np.array([1]*25).reshape(5,5)
n = mas[0].size
for i in range(1, n-1):
    for j in range(1, n-1):
        mas[i][j] = 0
for i in mas:
    print(*i)

1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1


Создать массив и отсортировать по убыванию

In [22]:
mas = np.random.random(10)
n = mas.size
mas = np.sort(mas)[::-1]
print(*mas)

0.9213897652102097 0.7393366774386162 0.6887856728990797 0.6599644673596544 0.6081023498794221 0.5176457094872383 0.4811793908224882 0.1635258708782873 0.145714166993276 0.06434060970136657


Создать матрицу. Вывести её форму, размер, размерность

In [24]:
matrix = np.array([9]*36).reshape(4,9)
print(matrix)
print("Форма матрицы = ", matrix.shape)
print("Размер матрицы =  matrix.size)
print("Размерность матрицы(число осей массива) = ", matrix.ndim)

[[9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]]
Форма матрицы (4, 9)
Размер матрицы 36
Размерность матрицы(число осей массива) 2


Pandas. Работа с данными как с таблицами. Импорт таблиц.
Найти евклидово расстояение между двумя Series(точками) a и b, не используя встроенную функцию.

In [35]:
import pandas as pd
import numpy  as np
a = pd.Series([121, 121, 32, 43, 121])
b = pd.Series([121, 121, 212, 43, 121])
c = 0
for i in range(a.size):
    c += (a[i] - b[i])**2
c = c**(1/2)
print("Евклидово расстояние между а и b, посчитанное с помощью встроенной функции = ", np.linalg.norm(a - b))
print("Евклидово расстояние между а и b, посчитанное с помощью формулы = ", np.linalg.norm(a - b))

Евклидово расстояние между а и b, посчитанное с помощью встроенной функции =  180.0
Евклидово расстояние между а и b, посчитанное с помощью формулы =  180.0


Сформировать из csv файла фрейм данных. Проанализировать его характеристики.

In [50]:
import pandas as pd
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.head(10)#первые строки
dataframe.tail(10)#последние строки
#print("Размерность фрейма = ", dataframe.shape)
#dataframe.describe()

Name PClass   Age     Sex  Survived  SexCode
1303      Yasbeck, Mr Antoni    3rd  27.0    male         0        0
1304     Yasbeck, Mrs Antoni    3rd  15.0  female         1        1
1305      Youssef, Mr Gerios    3rd   NaN    male         0        0
1306     Zabour, Miss Hileni    3rd   NaN  female         0        1
1307     Zabour, Miss Tamini    3rd   NaN  female         0        1
1308      Zakarian, Mr Artun    3rd  27.0    male         0        0
1309  Zakarian, Mr Maprieder    3rd  26.0    male         0        0
1310        Zenni, Mr Philip    3rd  22.0    male         0        0
1311        Lievens, Mr Rene    3rd  24.0    male         0        0
1312          Zimmerman, Leo    3rd  29.0    male         0        0

In [53]:
print("Размерность фрейма = ", dataframe.shape)
dataframe.describe()

Размерность фрейма =  (1313, 6)


Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

In [54]:
dataframe.iloc[12:20] #срез из таблицы

Name PClass   Age     Sex  \
12                     Aubert, Mrs Leontine Pauline    1st   NaN  female   
13                         Barkworth, Mr Algernon H    1st   NaN    male   
14                               Baumann, Mr John D    1st   NaN    male   
15   Baxter, Mrs James (Helene DeLaudeniere Chaput)    1st  50.0  female   
16                          Baxter, Mr Quigg Edmond    1st  24.0    male   
17                              Beattie, Mr Thomson    1st  36.0    male   
18                     Beckwith, Mr Richard Leonard    1st  37.0    male   
19  Beckwith, Mrs Richard Leonard (Sallie Monypeny)    1st  47.0  female   

    Survived  SexCode  
12         1        1  
13         1        0  
14         0        0  
15         1        1  
16         0        0  
17         0        0  
18         1        0  
19         1        1

In [55]:
dataframe[dataframe['Age'] == 18].head(10)

Name PClass   Age     Sex  \
201                  Penasco, Mr Victor de Satode    1st  18.0    male   
220                     Ryerson, Miss Emily Borie    1st  18.0  female   
236  Smith, Mrs Lucien Philip (Mary Eloise Hughes    1st  18.0  female   
258                            Taussig, Miss Ruth    1st  18.0  female   
324                       Andrew, Mr Edgar Samuel    2nd  18.0    male   
329                       Bailey, Mr Percy Andrew    2nd  18.0    male   
386                              Deacon, Mr Percy    2nd  18.0    male   
391                            Dibden, Mr William    2nd  18.0    male   
393                            Doling, Miss Elsie    2nd  18.0  female   
442                          Hiltunen, Miss Marta    2nd  18.0  female   

     Survived  SexCode  
201         0        0  
220         1        1  
236         1        1  
258         1        1  
324         0        0  
329         0        0  
386         0        0  
391         0        0  
393         1        1  
442         0        1

Загрузить фрейм. Выполнить нормализацию первого числового признака с использованием минимаксного преобразования, а второго с задействованием z-масштабирования.(sepal_length_cm,
sepal_width_cm)

In [58]:
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)
dataframe.head(10)#первые строки

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa
5              5.4             3.9              1.7             0.4  setosa
6              4.6             3.4              1.4             0.3  setosa
7              5.0             3.4              1.5             0.2  setosa
8              4.4             2.9              1.4             0.2  setosa
9              4.9             3.1              1.5             0.1  setosa

In [61]:
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)
feature1 = MinMaxScaler()
dataframe[['sepal_length_cm']] = feature1.fit_transform(dataframe[['sepal_length_cm']])
dataframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222             3.5              1.4             0.2   
1           0.166667             3.0              1.4             0.2   
2           0.111111             3.2              1.3             0.2   
3           0.083333             3.1              1.5             0.2   
4           0.194444             3.6              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667             3.0              5.2             2.3   
146         0.555556             2.5              5.0             1.9   
147         0.611111             3.0              5.2             2.0   
148         0.527778             3.4              5.4             2.3   
149         0.444444             3.0              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [62]:
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)
feature2 = StandardScaler()
dataframe[['sepal_width_cm']] = feature1.fit_transform(dataframe[['sepal_width_cm']])
dataframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0                5.1        0.625000              1.4             0.2   
1                4.9        0.416667              1.4             0.2   
2                4.7        0.500000              1.3             0.2   
3                4.6        0.458333              1.5             0.2   
4                5.0        0.666667              1.4             0.2   
..               ...             ...              ...             ...   
145              6.7        0.416667              5.2             2.3   
146              6.3        0.208333              5.0             1.9   
147              6.5        0.416667              5.2             2.0   
148              6.2        0.583333              5.4             2.3   
149              5.9        0.416667              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]